### ISSUE TITLE
Create Responsive Header

### ISSUE THREAD

**Issue by Emulation-accurate** [Emulation-accurate/EmulationWebsite#1]
we want a website header which is responsive and background colour will be #044CA1

**Comment by heisdinesh** [comment]
can i work on this issue @Emulation-accurate

**Comment by hemantwasthere** [comment]
@Emulation-accurate I want to work on this issue

**Comment by tarunvashishth** [comment]
Can you assign this to me?

**Comment by Ashank16** [comment]
Hey @Emulation-accurate, Can I work on this issue?

**Comment by Emulation-accurate** [comment]
> can i work on this issue @Emulation-accurate

Sure you can work please use React for this

**Comment by heisdinesh** [comment]
@Emulation-accurate  can we use tailwind css / bootstarp/ or plain css

**Comment by Emulation-accurate** [comment]
> @Emulation-accurate can we use tailwind css / bootstarp/ or plain css and may i know what should be there in header

Yes you can use plain css in header we want Events, Core team, About us, Our projects and one humburger menu icon for mobile view.

**Comment by tarunvashishth** [comment]
I have already worked on it, please assign it to me

**Comment by Emulation-accurate** [comment]
> I have already worked on it, please assign it to me

yes you can also work on this.

**Comment by tarunvashishth** [comment]
> > I have already worked on it, please assign it to me
> 
> yes you can also work on this.

I am not able to perform pull request.

**Comment by Emulation-accurate** [comment]
> > > I have already worked on it, please assign it to me
> > 
> > 
> > yes you can also work on this.
> 
> I am not able to perform pull request.

what is the issue

**Comment by tarunvashishth** [comment]
Only COMPARE CHANGES page is visible,
there is no Pull Request Button there.

**Comment by tarunvashishth** [comment]
> Only COMPARE CHANGES page is visible, there is no Pull Request Button there.



> Only COMPARE CHANGES page is visible,
> there is no Pull Request Button there.

Only COMPARE CHANGES page is visible,
there is no Pull Request Button there.

**Comment by tarunvashishth** [comment]
> > > > I have already worked on it, please assign it to me
> > > 
> > > 
> > > yes you can also work on this.
> > 
> > 
> > I am not able to perform pull request.
> 
> what is the issue

Only COMPARE CHANGES page is visible,
there is no Pull Request Button there.

**Comment by Emulation-accurate** [comment]
> Hey @Emulation-accurate, Can I work on this issue?

assigning to you please work on it
