### ISSUE TITLE
we want one certificate generator for our club

### ISSUE THREAD

**Issue by Emulation-accurate** [Emulation-accurate/EmulationWebsite#2]
#Certificate_Generator

**Comment by vaibhav-xt** [comment]
Please provide details on what it looks like and what should be in this certificate.

**Comment by Emulation-accurate** [comment]
> Please provide details on what it looks like and what should be in this certificate.

1. Our club logo and name should be there.
2.  We will provide certificate of internship completion for three domain Web development intern/mentor , Android Development intern/mentor, competitive programing mentor in which intern/mentor name, duration of internship, and their name should be present. We need one appreciation certificate also if any candidate perform well in their work we can give him appreciation certificate.

3. Our college logo is also there somewhere so that I will show we are representing our college also.

**Comment by Emulation-accurate** [comment]
Our logo : ![IMG-20221001-WA0005](https://user-images.githubusercontent.com/114817503/194697067-6d3745fe-282e-470e-b2cf-796a2a6d5a1e.jpg)

**Comment by vaibhav-xt** [comment]
I made the pull request but It was not accepted

**Comment by Emulation-accurate** [comment]
Thanks for your contribution
