### ISSUE TITLE
make the header file separately.

### ISSUE THREAD

**Issue by Emulation-accurate** [Emulation-accurate/EmulationWebsite#24]
make the header file separately. so that we can use that header  everywhere.

**Comment by vaibhav-xt** [comment]
Do You want this header page? I recently made this as a project it is fully responsive and compatible with all devices.

Suppose you are talking about this page. then get assigned to me and please tell me what you want in this header.
For Example about, services, and portfolio in the header.

![Screenshot (39)](https://user-images.githubusercontent.com/90946899/195341907-c229a070-594d-4013-954a-659798ef55a6.png)
