### ISSUE TITLE
Create our project page for our club

### ISSUE THREAD

**Issue by Emulation-accurate** [Emulation-accurate/EmulationWebsite#5]

**Comment by anuragchauhan766** [comment]
what you need in this?
can you specify?

**Comment by Emulation-accurate** [comment]
> what you need in this? can you specify?

we want to showcase projects on this page you take reference from other website.

**Comment by vaibhav-xt** [comment]
Yes, I can make this page.  Please get assign me.

**Comment by Emulation-accurate** [comment]
Assigned please work on certificate generator and this issue.
