### ISSUE TITLE
Create Homepage of our club website.

### ISSUE THREAD

**Issue by Emulation-accurate** [Emulation-accurate/EmulationWebsite#6]

**Comment by Lovegupta112** [comment]
I want to make homepage , please assign me

**Comment by anuragchauhan766** [comment]
please assign it to me , i have already started working on the design

**Comment by shwetaeladi07** [comment]
Hello, can you please explain me what all things are to be included in your homepage?

**Comment by Gola-k** [comment]
please correct the spelling of hacktoberfest label you have written hactoberfest which is wrong, correct is hacktoberfest

**Comment by Emulation-accurate** [comment]
> please correct the spelling of hacktoberfest label you have written hactoberfest which is wrong, correct is hacktoberfest

corrected thanks :)
